name: Deploy program

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    env:
      SSH_KEY: ${{ secrets.UPDATE_PROJECT_SSH_KEY }}
      SSH_USER: ${{ secrets.UPDATE_PROJECT_USER }}
      SSH_IP: ${{ secrets.UPDATE_PROJECT_IP }}
      REMOTE_SCRIPT_PATH: ${{ secrets.UPDATE_PROJECT_FILE_PATH }}
    steps:
      - uses: actions/checkout@v4

      - name: Test SSH Connection
        run: ssh $SSH_USER@$SSH_IP "echo Connection Successful"

      - name: Reset repository
        run: |
          cd /Ja-Man-Sem-6-Repo
          ls
          cd Ja-Man-Sem-6
          ls
          git reset --hard HEAD
          cd ..

      - name: Set up virtual environment
        run: ssh $SSH_KEY $SSH_USER@$SSH_IP $REMOTE_SCRIPT_PATH